"""
Main application window.

This module is pure presentation: it builds customtkinter
widgets and delegates all backend work to
GuardianController.  No business logic lives here.

Run with:

    python -m ui.app
"""

try:
    import customtkinter as ctk

except ImportError:

    raise SystemExit(
        "customtkinter is required for the "
        "desktop UI.\n\n"
        "Install it with:\n"
        "  pip install customtkinter\n\n"
        "Or install all project dependencies:\n"
        "  pip install -r requirements.txt"
    )

from ui.app_controller import GuardianController

from ui.navigation import NAV_ITEMS

from ui.views import register_views


class GuardianApp(ctk.CTk):
    """
    Top-level application window.

    Layout
    ------
    ┌─────────┬──────────────────────┐
    │Sidebar  │  Content Area        │
    │(nav)    │                      │
    ├─────────┴──────────────────────┤
    │Status Bar                      │
    └────────────────────────────────┘
    """

    def __init__(self, controller=None):
        super().__init__()

        self.ctrl = (
            controller or GuardianController()
        )

        self.ctrl._root = self

        self.title("AI Laptop Guardian")

        self.geometry("1100x700")

        self.minsize(880, 560)

        self._view_cache = {}

        self._active_key = None

        self._nav_buttons = {}

        self._view_classes = register_views()

        self._status_var = ctk.StringVar(
            value="Status: Initializing..."
        )

        self._shutting_down = False

        self._onboarding_mode = False

        self._onboarding_container = None

        self._build_layout()

        self._bind_status_event()

        self.protocol(
            "WM_DELETE_WINDOW", self._on_close
        )

        self.after(200, self._show_initial_view)

    # =====================================================
    # LAYOUT
    # =====================================================

    def _build_layout(self):
        self.grid_columnconfigure(1, weight=1)

        self.grid_rowconfigure(0, weight=1)

        # --- Sidebar ---

        self._sidebar = ctk.CTkFrame(
            self, width=180, corner_radius=0
        )

        self._sidebar.grid(
            row=0, column=0, sticky="nsew",
        )

        self._sidebar.grid_propagate(False)

        ctk.CTkLabel(
            self._sidebar,
            text="AI LAPTOP\nGUARDIAN",
            font=ctk.CTkFont(
                size=13, weight="bold"
            ),
            pady=18,
        ).pack(fill="x")

        for key, label in NAV_ITEMS:
            btn = ctk.CTkButton(
                self._sidebar,
                text=label,
                anchor="w",
                height=38,
                corner_radius=6,
                fg_color="transparent",
                text_color="gray80",
                hover_color=("gray75", "gray25"),
                command=lambda k=key: (
                    self.show_view(k)
                ),
            )

            btn.pack(
                fill="x", padx=10, pady=2,
            )

            self._nav_buttons[key] = btn

        # --- Content ---

        self._content = ctk.CTkFrame(
            self, corner_radius=0
        )

        self._content.grid(
            row=0, column=1, sticky="nsew",
        )

        self._content.grid_columnconfigure(
            0, weight=1
        )

        self._content.grid_rowconfigure(
            0, weight=1
        )

        # --- Status bar ---

        status_bar = ctk.CTkLabel(
            self,
            textvariable=self._status_var,
            anchor="w",
            height=32,
            padx=16,
            font=ctk.CTkFont(size=11),
            fg_color=("gray90", "gray15"),
        )

        status_bar.grid(
            row=1, column=0, columnspan=2,
            sticky="ew",
        )

    # =====================================================
    # STATUS EVENT (generated by views)
    # =====================================================

    def _bind_status_event(self):
        self.bind(
            "<<StatusUpdate>>", self._on_status,
        )

    def _on_status(self, event):
        data = getattr(event, "data", None)

        if data:
            self._status_var.set(
                f"Status: {data}"
            )

    # =====================================================
    # VIEW SWITCHING
    # =====================================================

    def _show_initial_view(self):
        import app.state as state_mod

        if not state_mod.is_onboarding_completed():
            self._show_onboarding()
            return

        self._show_main_ui()

    # =====================================================
    # ONBOARDING MODE
    # =====================================================

    def _show_onboarding(self):
        self._onboarding_mode = True

        for child in self._content.winfo_children():
            child.grid_forget()

        for btn in self._nav_buttons.values():
            btn.pack_forget()

        self._sidebar.winfo_children()[0].pack_forget()
        for btn in list(self._nav_buttons.values()):
            btn.pack_forget()
        for child in self._sidebar.winfo_children():
            child.pack_forget()

        ctk.CTkLabel(
            self._sidebar,
            text="AI LAPTOP\nGUARDIAN",
            font=ctk.CTkFont(
                size=13, weight="bold"
            ),
            pady=18,
        ).pack(fill="x")

        self._onboarding_container = ctk.CTkFrame(
            self._content, fg_color="transparent"
        )
        self._onboarding_container.grid(
            row=0, column=0, sticky="nsew",
        )

        from ui.views.onboarding_view import OnboardingView

        OnboardingView(
            self._onboarding_container,
            self.ctrl,
            on_finish=self._on_onboarding_finish,
        ).pack(fill="both", expand=True)

    def _on_onboarding_finish(self):
        self._onboarding_mode = False

        if self._onboarding_container:
            self._onboarding_container.destroy()
            self._onboarding_container = None

        self._show_main_ui()

    def _show_main_ui(self):
        for child in self._content.winfo_children():
            child.grid_forget()

        self._rebuild_sidebar_nav()

        self._show_initial_view_after_onboarding()

    def _rebuild_sidebar_nav(self):
        for child in self._sidebar.winfo_children():
            child.pack_forget()

        ctk.CTkLabel(
            self._sidebar,
            text="AI LAPTOP\nGUARDIAN",
            font=ctk.CTkFont(
                size=13, weight="bold"
            ),
            pady=18,
        ).pack(fill="x")

        self._nav_buttons.clear()

        for key, label in NAV_ITEMS:
            btn = ctk.CTkButton(
                self._sidebar,
                text=label,
                anchor="w",
                height=38,
                corner_radius=6,
                fg_color="transparent",
                text_color="gray80",
                hover_color=("gray75", "gray25"),
                command=lambda k=key: (
                    self.show_view(k)
                ),
            )

            btn.pack(
                fill="x", padx=10, pady=2,
            )

            self._nav_buttons[key] = btn

    def _show_initial_view_after_onboarding(self):
        self.show_view("dashboard")
        self._status_var.set("Status: Ready")

    def show_view(self, key):
        if key not in self._view_classes:
            return

        for child in self._content.winfo_children():
            child.grid_forget()

        if key not in self._view_cache:
            cls = self._view_classes[key]

            self._view_cache[key] = cls(
                self._content, self.ctrl
            )

        view = self._view_cache[key]

        view.grid(
            row=0, column=0, sticky="nsew",
        )

        self._active_key = key

        for nav_key, btn in (
            self._nav_buttons.items()
        ):
            if nav_key == key:
                btn.configure(
                    fg_color=(
                        "gray75", "gray25"
                    ),
                    text_color="white",
                )
            else:
                btn.configure(
                    fg_color="transparent",
                    text_color="gray80",
                )

        if hasattr(view, "refresh"):
            view.refresh()

    # =====================================================
    # CLEAN SHUTDOWN
    # =====================================================

    def _on_close(self):
        """Handle window close button gracefully."""
        self._shutting_down = True
        self.ctrl._shutting_down = True

        self._view_cache.clear()

        try:
            super().destroy()
        except Exception:
            pass

    def destroy(self):
        self._shutting_down = True
        self.ctrl._shutting_down = True

        for child in self._content.winfo_children():
            try:
                child.destroy()
            except Exception:
                pass

        self._view_cache.clear()

        try:
            super().destroy()
        except Exception:
            pass


def main():
    """Launch the desktop application with startup validation."""
    from app.env_check import run_all_checks

    checks = run_all_checks()
    critical = [c for c in checks if not c.get("optional") and not c["ok"]]
    if critical:
        msgs = "\n".join(
            f"  [{c['name']}] {c['detail']}" for c in critical
        )
        raise SystemExit(
            "Environment check failed:\n" + msgs
        )

    app = GuardianApp()

    app.mainloop()


if __name__ == "__main__":
    main()
