"""
Main application window.

This module is pure presentation: it builds customtkinter
widgets and delegates all backend work to
GuardianController.  No business logic lives here.

Run with:

    python -m ui.app
"""

try:
    import customtkinter as ctk

except ImportError:

    raise SystemExit(
        "customtkinter is required for the "
        "desktop UI.\n\n"
        "Install it with:\n"
        "  pip install customtkinter\n\n"
        "Or install all project dependencies:\n"
        "  pip install -r requirements.txt"
    )

from ui.app_controller import GuardianController

from ui.navigation import NAV_ITEMS

from ui.views import register_views


class GuardianApp(ctk.CTk):
    """
    Top-level application window.

    Layout
    ------
    ┌─────────┬──────────────────────┐
    │Sidebar  │  Content Area        │
    │(nav)    │                      │
    ├─────────┴──────────────────────┤
    │Status Bar                      │
    └────────────────────────────────┘
    """

    def __init__(self, controller=None):
        super().__init__()

        self.ctrl = (
            controller or GuardianController()
        )

        self.title("AI Laptop Guardian")

        self.geometry("1100x700")

        self.minsize(880, 560)

        self._view_cache = {}

        self._active_key = None

        self._nav_buttons = {}

        self._view_classes = register_views()

        self._status_var = ctk.StringVar(
            value="Status: Initializing..."
        )

        self._build_layout()

        self._bind_status_event()

        self.after(200, self._show_initial_view)

    # =====================================================
    # LAYOUT
    # =====================================================

    def _build_layout(self):
        self.grid_columnconfigure(1, weight=1)

        self.grid_rowconfigure(0, weight=1)

        # --- Sidebar ---

        sidebar = ctk.CTkFrame(
            self, width=180, corner_radius=0
        )

        sidebar.grid(
            row=0, column=0, sticky="nsew",
        )

        sidebar.grid_propagate(False)

        ctk.CTkLabel(
            sidebar,
            text="AI LAPTOP\nGUARDIAN",
            font=ctk.CTkFont(
                size=13, weight="bold"
            ),
            pady=18,
        ).pack(fill="x")

        for key, label in NAV_ITEMS:
            btn = ctk.CTkButton(
                sidebar,
                text=label,
                anchor="w",
                height=38,
                corner_radius=6,
                fg_color="transparent",
                text_color="gray80",
                hover_color=("gray75", "gray25"),
                command=lambda k=key: (
                    self.show_view(k)
                ),
            )

            btn.pack(
                fill="x", padx=10, pady=2,
            )

            self._nav_buttons[key] = btn

        # --- Content ---

        self._content = ctk.CTkFrame(
            self, corner_radius=0
        )

        self._content.grid(
            row=0, column=1, sticky="nsew",
        )

        self._content.grid_columnconfigure(
            0, weight=1
        )

        self._content.grid_rowconfigure(
            0, weight=1
        )

        # --- Status bar ---

        status_bar = ctk.CTkLabel(
            self,
            textvariable=self._status_var,
            anchor="w",
            height=32,
            padx=16,
            font=ctk.CTkFont(size=11),
            fg_color=("gray90", "gray15"),
        )

        status_bar.grid(
            row=1, column=0, columnspan=2,
            sticky="ew",
        )

    # =====================================================
    # STATUS EVENT (generated by views)
    # =====================================================

    def _bind_status_event(self):
        self.bind(
            "<<StatusUpdate>>", self._on_status,
        )

    def _on_status(self, event):
        data = getattr(event, "data", None)

        if data:
            self._status_var.set(
                f"Status: {data}"
            )

    # =====================================================
    # VIEW SWITCHING
    # =====================================================

    def _show_initial_view(self):
        self.show_view("dashboard")

        self._status_var.set("Status: Ready")

    def show_view(self, key):
        if key not in self._view_classes:
            return

        for child in self._content.winfo_children():
            child.grid_forget()

        if key not in self._view_cache:
            cls = self._view_classes[key]

            self._view_cache[key] = cls(
                self._content, self.ctrl
            )

        view = self._view_cache[key]

        view.grid(
            row=0, column=0, sticky="nsew",
        )

        self._active_key = key

        for nav_key, btn in (
            self._nav_buttons.items()
        ):
            if nav_key == key:
                btn.configure(
                    fg_color=(
                        "gray75", "gray25"
                    ),
                    text_color="white",
                )
            else:
                btn.configure(
                    fg_color="transparent",
                    text_color="gray80",
                )

        if hasattr(view, "refresh"):
            view.refresh()

    # =====================================================
    # CLEAN SHUTDOWN
    # =====================================================

    def destroy(self):
        for child in self._content.winfo_children():
            try:
                child.destroy()
            except Exception:
                pass

        self._view_cache.clear()

        super().destroy()


def main():
    app = GuardianApp()

    app.mainloop()


if __name__ == "__main__":
    main()
